import { StyleSheet } from 'react-native';
import {
  colors,
  fonts,
  spacing,
  themedStyles,
} from '@/lib/theme';

/** Shared by the active-workout screen and its cards and set rows. */
export const activeWorkoutStyles = themedStyles(() => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bg,
  },
  muted: {
    color: colors.textMuted,
    marginBottom: spacing.md,
  },
  secondaryBtn: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.textDim,
    borderRadius: 6,
  },
  secondaryBtnText: {
    color: colors.text,
    fontWeight: '600',
  },
  stats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  stat: {
    alignItems: 'center',
  },
  statV: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
  },
  statL: {
    fontSize: 11,
    color: colors.textDim,
    marginTop: 4,
    letterSpacing: 0.5,
  },
  empty: {
    color: colors.textDim,
    textAlign: 'center',
    paddingVertical: spacing.xl,
  },
  card: {
    backgroundColor: colors.surface,
    marginHorizontal: spacing.md,
    marginVertical: spacing.sm,
    padding: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardCurrent: {
    borderColor: colors.accent,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  cardCounter: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDim,
    letterSpacing: 0.5,
  },
  moveRow: { flexDirection: 'row', gap: 8, marginRight: 10 },
  plateHint: { paddingVertical: 8 },
  supersetChip: { borderWidth: 1, borderColor: colors.accent, color: colors.accent },
  plateHintText: { color: colors.textMuted, fontSize: 13, fontWeight: '600' },
  moveBtn: {
    width: 36,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.borderBright,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moveBtnOff: { opacity: 0.3 },
  moveBtnText: { color: colors.text, fontSize: 16, fontWeight: '700' },
  stateChip: {
    fontSize: 12,
    fontWeight: '700',
    backgroundColor: colors.textDim,
    color: colors.bg,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 4,
  },
  stateChipCurrent: {
    backgroundColor: colors.accent,
    color: colors.onAccent,
  },
  exTile: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  exThumb: {
    width: 44,
    height: 44,
    backgroundColor: colors.textDim,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
    overflow: 'hidden',
  },
  exThumbImg: { width: '100%', height: '100%', backgroundColor: '#ffffff' },
  exThumbText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.bg,
  },
  exName: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
  },
  chipRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
    flexWrap: 'wrap',
  },
  chip: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
    backgroundColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 4,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
    flexWrap: 'wrap',
  },
  outlineBtn: {
    flex: 1,
    minWidth: '45%',
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    alignItems: 'center',
  },
  outlineBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  accentBtn: {
    flex: 1,
    minWidth: '45%',
    paddingVertical: spacing.sm,
    backgroundColor: colors.accent,
    borderRadius: 6,
    alignItems: 'center',
  },
  accentBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.onAccent,
  },
  photoPanel: {
    backgroundColor: colors.border,
    borderRadius: 8,
    padding: spacing.md,
    marginBottom: spacing.md,
    alignItems: 'center',
  },
  photoPlaceholder: {
    width: 100,
    height: 100,
    backgroundColor: colors.bg,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  photoAdd: { borderWidth: 2, borderStyle: 'dashed', borderColor: colors.accent },
  photoAddIcon: { fontSize: 36, color: colors.accent, fontWeight: '300' },
  photoInitials: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.textDim,
  },
  photoHint: {
    fontSize: 12,
    color: colors.textDim,
    marginTop: spacing.xs,
    textAlign: 'center',
  },
  photoCaption: {
    fontSize: 12,
    color: colors.textDim,
  },
  photoImage: {
    width: '100%',
    height: 160,
    marginBottom: spacing.sm,
    backgroundColor: '#ffffff',
    borderRadius: 6,
  },
  noteText: {
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: spacing.md,
  },
  noteInput: {
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
    padding: spacing.sm,
    marginBottom: spacing.md,
    minHeight: 44,
  },
  lastLine: {
    fontSize: 13,
    color: colors.textDim,
    marginBottom: spacing.md,
  },
  setHeader: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: spacing.xs,
  },
  col: {
    flex: 1,
  },
  colSet: {
    width: 30,
    flex: 0,
  },
  colNum: {
    flex: 1,
  },
  colDone: {
    width: 36,
    flex: 0,
  },
  // The set number was unstyled, so it drew near-black on the dark card.
  setLabel: { color: colors.textMuted, fontSize: 14, fontWeight: '700', textAlign: 'center' },
  trackRow: { flexDirection: 'row', gap: 8, marginBottom: spacing.sm },
  trackChip: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  trackChipOn: { borderColor: colors.accent, backgroundColor: colors.surfaceAlt },
  trackChipText: { color: colors.textMuted, fontSize: 13, fontFamily: fonts.bodySemi },
  trackChipTextOn: { color: colors.text },
  loadLine: { color: colors.textMuted, fontSize: 12.5, marginTop: spacing.sm, fontFamily: fonts.body },
  headText: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  setRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  warmupRow: {
    backgroundColor: colors.border,
  },
  warmText: {
    color: colors.textDim,
  },
  doneRow: {
    opacity: 0.75,
  },
  numGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  stepBtn: {
    width: 34,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtn: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.accent,
  },
  numInput: {
    flex: 1,
    minWidth: 40,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    backgroundColor: colors.bg,
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: spacing.xs,
  },
  tickCircle: {
    overflow: 'visible',
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: colors.borderBright,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: spacing.xs,
  },
  prBadge: { position: 'absolute', top: -8, right: -8 },
  prBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.surface,
  },
  prBannerHead: { color: colors.text, fontFamily: fonts.pixel, fontSize: 6, letterSpacing: 0.7 },
  prBannerNote: { color: colors.textMuted, fontSize: 13, marginTop: 4 },
  tickOn: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  tickText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDim,
  },
  tickTextOn: {
    color: colors.onAccent,
  },
  actionGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
    flexWrap: 'wrap',
  },
  dashedBtn: {
    flex: 1,
    minWidth: '45%',
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.border,
    borderRadius: 6,
    alignItems: 'center',
  },
  dashedBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  footer: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  addBtn: {
    flex: 1,
    paddingVertical: spacing.md,
    backgroundColor: colors.accent,
    borderRadius: 6,
    alignItems: 'center',
  },
  addBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.onAccent,
  },
  discardLink: {
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
  },
  discardLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDim,
  },
}));
