#!/usr/bin/env node
/**
 * Build the RepDB exercise bundle into generated/repdb/ (gitignored).
 *
 *   node scripts/build-repdb.mjs                 # fetch the pinned RepDB commit
 *   node scripts/build-repdb.mjs --from <dir>    # use a local clone instead
 *
 * RepDB's free tier allows the data and images inside an app, with a visible
 * "Exercise data by RepDB (repdb.co)" credit, and forbids republishing them as
 * a dataset. This repository is public, so nothing RepDB-derived is committed:
 * the APK workflow runs this script, Metro bundles the output into the app,
 * and a checkout without it builds and tests normally with no RepDB exercises
 * (see metro.config.js and lib/repdb-stub.ts).
 */
import { execFileSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { mapRepdb } from './repdb-map.mjs';

/** Pinned so a build is reproducible and a new RepDB release is a deliberate change. */
const REPDB_REPO = 'https://github.com/RepDB/exercise-dataset';
const REPDB_COMMIT = '9ed9357f09c7566ea0256c57ebd6374ebb8b575e';
const IMAGE_SIZE = 256;

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'generated/repdb');
const imgDir = path.join(outDir, 'images');

function sourceDir() {
  const i = process.argv.indexOf('--from');
  if (i > 0 && process.argv[i + 1]) return path.resolve(process.argv[i + 1]);
  const dir = path.join(root, 'node_modules/.cache/repdb');
  if (!fs.existsSync(path.join(dir, '.git'))) {
    fs.mkdirSync(dir, { recursive: true });
    execFileSync('git', ['init', '-q'], { cwd: dir });
    execFileSync('git', ['remote', 'add', 'origin', REPDB_REPO], { cwd: dir });
  }
  execFileSync('git', ['fetch', '-q', '--depth', '1', 'origin', REPDB_COMMIT], { cwd: dir, stdio: 'inherit' });
  execFileSync('git', ['checkout', '-q', '--force', REPDB_COMMIT], { cwd: dir });
  return dir;
}

const src = sourceDir();
const rows = JSON.parse(fs.readFileSync(path.join(src, 'exercises.json'), 'utf8')).exercises;
const existing = JSON.parse(fs.readFileSync(path.join(root, 'assets/data/exercises.json'), 'utf8')).map(
  (e) => e.name
);

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(imgDir, { recursive: true });

// Images first, so the mapping only references ones that actually exist.
const imageKeys = new Set();
for (const r of rows) {
  for (const pose of ['start', 'peak']) {
    const rel = r.images?.flat?.[pose];
    if (!rel) continue;
    const from = path.join(src, rel);
    if (!fs.existsSync(from)) continue;
    const key = `${r.id}-${pose}`;
    await sharp(from).resize(IMAGE_SIZE, IMAGE_SIZE, { fit: 'inside' }).webp({ quality: 80 }).toFile(path.join(imgDir, `${key}.webp`));
    imageKeys.add(key);
  }
}

const { exercises, duplicates, unmapped } = mapRepdb(rows, existing, imageKeys);
if (unmapped.length > 0) {
  // A new RepDB value would otherwise ship as an exercise missing from the
  // muscle map or the equipment filter. Add it to scripts/repdb-map.mjs.
  console.error(`Unmapped RepDB values: ${unmapped.join(', ')}`);
  process.exit(1);
}

// Drop images for exercises skipped as duplicates of the bundled catalogue.
const used = new Set(exercises.flatMap((e) => e.images.map((i) => i.replace(/^repdb\//, ''))));
for (const key of imageKeys) {
  if (!used.has(key)) fs.rmSync(path.join(imgDir, `${key}.webp`));
}

const json = JSON.stringify(exercises);
const checksum = crypto.createHash('sha256').update(json).digest('hex').slice(0, 16);
fs.writeFileSync(path.join(outDir, 'exercises.json'), json);

const requires = [...used]
  .sort()
  .map((key) => `  ${JSON.stringify(key)}: require('./images/${key}.webp'),`)
  .join('\n');
fs.writeFileSync(
  path.join(outDir, 'index.ts'),
  `// Generated by scripts/build-repdb.mjs from RepDB ${REPDB_COMMIT}. Do not commit.
import type { RepdbBundle } from '@/lib/repdb-stub';
import exercises from './exercises.json';

export const REPDB: RepdbBundle = {
  commit: ${JSON.stringify(REPDB_COMMIT)},
  checksum: ${JSON.stringify(checksum)},
  exercises: exercises as RepdbBundle['exercises'],
  images: {
${requires}
  },
};
`
);

const bytes = [...used].reduce((n, key) => n + fs.statSync(path.join(imgDir, `${key}.webp`)).size, 0);
console.log(
  `RepDB ${REPDB_COMMIT.slice(0, 7)}: ${exercises.length} exercises added, ${duplicates.length} already bundled, ` +
    `${used.size} images (${(bytes / 1048576).toFixed(1)} MB), checksum ${checksum}`
);
