import { StyleSheet } from 'react-native';
import { colors, spacing, themedStyles } from '@/lib/theme';

/** Shared by the Settings screen and its sections. */
export const settingsStyles = themedStyles(() => StyleSheet.create({
  themeDot: { width: 22, height: 22, borderRadius: 11 },
  browseBtn: { paddingVertical: 10 },
  browseText: { color: colors.accent, fontSize: 13, fontWeight: '700' },
  container: { flex: 1, backgroundColor: colors.bg, padding: spacing.lg },
  center: {
    flex: 1,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  muted: { color: colors.textMuted, lineHeight: 20, marginBottom: spacing.md },
  label: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 6,
    marginTop: spacing.sm,
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 16,
  },
  unitRow: { flexDirection: 'row', gap: spacing.sm },
  unitChip: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
  },
  unitChipOn: { borderColor: colors.accent, backgroundColor: colors.track },
  optRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: spacing.md,
    paddingVertical: 11,
    marginBottom: 6,
  },
  optRowOn: { borderColor: colors.accent, backgroundColor: colors.track },
  optName: { color: colors.text, fontWeight: '700', fontSize: 14 },
  optDetail: { color: colors.textMuted, fontSize: 11.5, lineHeight: 16, marginTop: 2 },
  optFactor: { color: colors.textMuted, fontSize: 12.5, fontWeight: '700' },
  calcCard: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: spacing.md,
    marginTop: spacing.sm,
    gap: 4,
  },
  calcRow: { color: colors.textMuted, fontSize: 13 },
  calcNum: { color: colors.text, fontWeight: '800', fontSize: 15 },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    padding: spacing.md,
  },
  toggleTitle: { color: colors.text, fontWeight: '700', fontSize: 14, marginBottom: 3 },
  switch: {
    width: 46,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.track,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    padding: 2,
  },
  switchOn: { backgroundColor: colors.accent, borderColor: colors.accent },
  knob: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.textMuted,
  },
  knobOn: { backgroundColor: colors.onAccent, alignSelf: 'flex-end' },
  unitText: { color: colors.textMuted, fontWeight: '800' },
  unitTextOn: { color: colors.accent },
  save: {
    marginTop: spacing.lg,
    backgroundColor: colors.accent,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  saveText: { color: colors.chipActiveText, fontWeight: '900', fontSize: 16 },
  aiCard: {
    marginTop: spacing.lg,
    padding: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  aiTitle: { color: colors.text, fontWeight: '800', marginBottom: 6, fontSize: 16 },
  charCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    marginBottom: spacing.md,
  },
  providerWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  providerChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  providerChipOn: { borderColor: colors.accent, backgroundColor: colors.track },
  providerText: { color: colors.textMuted, fontWeight: '700', fontSize: 12 },
  providerTextOn: { color: colors.accent },
  hint: { color: colors.textMuted, fontSize: 12, marginTop: 8, lineHeight: 16 },
  clearKey: {
    marginTop: spacing.md,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  clearKeyConfirm: { borderColor: colors.danger },
  clearKeyText: { color: colors.danger, fontWeight: '700', fontSize: 13 },
}));
